name: Run Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, opcache
        tools: phpize, php-config

    - name: Install PHP development package
      run: |
        sudo apt-get update
        sudo apt-get install -y php8.1-dev

    - name: Prepare for build
      run: |
        phpize
        ./configure
        make
        sudo make install

    - name: Check extension is loaded
      run: |
        php -m

    - name: Run tests
      run: |
        export NO_INTERACTION=1
        EXT_DIR=$(php -r "echo ini_get('extension_dir');")
        export TEST_PHP_ARGS="-d zend_extension=${EXT_DIR}/opcache.so -d opcache.enable=1 -d opcache.enable_cli=1 -d open_basedir= -d output_buffering=0 -d memory_limit=-1"
        echo $TEST_PHP_ARGS
        make test || true
        echo "Log file"
        cat tests/007.log
        echo "Diff"
        cat tests/007.diff
        echo "Output"
        cat tests/007.out
        echo "Expected"
        cat tests/007.exp

